In [41]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np

In [42]:
df = pd.read_csv('CommentToxicity-main/jigsaw-toxic-comment-classification-challenge/train.csv/train.csv')
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [43]:
df.tail()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0

Preprocessing

In [44]:
from tensorflow.keras.layers import TextVectorization

In [45]:
X = df['comment_text']
y = df[df.columns[2:]].values

In [46]:
#number of words per vocab
MAX_FEATURES = 200000

In [47]:
vectorizer = TextVectorization(max_tokens = MAX_FEATURES, output_sequence_length = 1800, output_mode = 'int')

In [48]:
vectorizer.adapt(X.values)

In [ ]:
vectorizer.get_vocabulary()

In [50]:
vectorized_text = vectorizer(X.values)

In [ ]:
vectorized_text

In [52]:
#MAP - CACHE - SHUFFLE - BATCH - PREFETCH
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)

In [53]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.7))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.7))

In [ ]:
train_generator = train.as_numpy_iterator()
#cycle through different training batches
train_generator.next()

Create Sequential Model

In [55]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [56]:
model = Sequential()
#Create embedding layer
model.add(Embedding(MAX_FEATURES+1, 32))
#Bidirectional LSTM layer
model.add(Bidirectional(LSTM(32, activation = 'tanh')))
#Feature extractor fully connected layers
model.add(Dense(128, activation = 'relu'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
#Final layer
model.add(Dense(6, activation = 'sigmoid'))

In [57]:
model.compile(loss = 'BinaryCrossentropy', optimizer = 'Adam')

In [ ]:
model.summary()

In [ ]:
history = model.fit(train, epochs = 1, validation_data = val)

Predict

In [63]:
batch = test.as_numpy_iterator().next()

In [64]:
input_text = vectorizer("you black fatso")

In [65]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [66]:
model.predict(np.expand_dims(input_text, 0))

array([[0.98362106, 0.293944  , 0.90215236, 0.03551465, 0.7057603 ,
        0.17022339]], dtype=float32)

Evaluate

In [58]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [59]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [ ]:
for batch in test.as_numpy_iterator():
    # Unpack the batch
    X_true, y_true = batch
    # Make a prediction
    yhat = model.predict(X_true)

    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()

    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

In [62]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.8055649995803833, Recall:0.6734752058982849, Accuracy:0.46492984890937805